<?php

namespace VauretAdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActualityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualityRepository extends EntityRepository
{
}
