VauretAdminBundle\Entity\Mail:
    type: entity
    table: mail
    repositoryClass: VauretAdminBundle\Repository\MailRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        mail:
            type: string
            length: 255
    lifecycleCallbacks: {  }
